### ISSUE TITLE
maybe to complex ...so it costs live time

### ISSUE THREAD

**Issue by olli0815** [rcdailey/nextcloud-cronjob#13] opened 2022-03-04 17:09 UTC
Will search for Nexcloud container as a Docker Compose service

Project: nextcloud, Service: nextcloud-app

ERROR: Unable to find the Nextcloud container

Will search for Nexcloud container as a Docker Compose service

Project: nextcloud, Service: nextcloud-app

ERROR: Unable to find the Nextcloud container

**Comment by rcdailey** [comment] 2022-03-04 17:16
This issue isn't well formed, and the title is confusing. Please edit & clarify with details.

**Comment by arsevka** [comment] 2022-03-07 20:29
In my case find-container.sh searches for "nextcloud_app", but docker ps reports "nextcloud-app". Fixed by replacing underscore with dash find-container.sh line 5.
`contents of containerName var
nextcloud_app

output of docker ps --format '{{.Names}},{{.ID}}'
nextcloud-cron-1,47b1abd2fa1f
nextcloud-db-1,7b771e799eee
nextcloud-app-1,9ddb04783fb7
nextcloud-proxy-1,303881db3503`

**Comment by rcdailey** [comment] 2022-03-08 17:17
This is a duplicate of #10

**Closed as completed by rcdailey** 2022-03-08 17:17 UTC
